/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : string,
  'status' : ComplaintStatus,
  'studentId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'priority' : Priority,
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'inProgress' : null } |
  { 'registered' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Authenticated users only: submit a new complaint on behalf of themselves.
   * / The studentId is taken from the caller principal, not a parameter, so a
   * / user cannot file a complaint under someone else's identity.
   */
  'createComplaint' : ActorMethod<[string, string, Priority], undefined>,
  /**
   * / Admin-only: view every complaint in the system.
   */
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Authenticated users can fetch a complaint they own; admins can fetch any.
   */
  'getComplaintById' : ActorMethod<[string], Complaint>,
  /**
   * / Admin-only: filter complaints by status.
   */
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  /**
   * / Returns all complaints belonging to the caller.
   * / Admins may pass any principal; regular users may only query themselves.
   */
  'getComplaintsByStudent' : ActorMethod<[Principal], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Admins can update any complaint status; a student can only update their own.
   */
  'updateComplaintStatus' : ActorMethod<[string, ComplaintStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];