/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'departmentId' : IDL.Opt(IDL.Nat),
});
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
  'registered' : IDL.Null,
});
export const Time = IDL.Int;
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'status' : ComplaintStatus,
  'studentId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'priority' : Priority,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'headOfDepartment' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createComplaint' : IDL.Func([IDL.Text, IDL.Text, Priority], [], []),
  'createDepartment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'deleteAccount' : IDL.Func([], [IDL.Text], []),
  'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
  'findUsersByDepartmentId' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintById' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getComplaintsByDepartment' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComplaintsByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getDepartment' : IDL.Func([IDL.Nat], [Department], ['query']),
  'getDepartmentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDepartmentsByHeadOfDepartment' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Department)],
      ['query'],
    ),
  'getSortedComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDepartment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'updateDepartmentComplaintStatus' : IDL.Func(
      [IDL.Text, ComplaintStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'departmentId' : IDL.Opt(IDL.Nat),
  });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
    'registered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'status' : ComplaintStatus,
    'studentId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'headOfDepartment' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createComplaint' : IDL.Func([IDL.Text, IDL.Text, Priority], [], []),
    'createDepartment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'deleteAccount' : IDL.Func([], [IDL.Text], []),
    'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
    'findUsersByDepartmentId' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintById' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getComplaintsByDepartment' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComplaintsByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getDepartment' : IDL.Func([IDL.Nat], [Department], ['query']),
    'getDepartmentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDepartmentsByHeadOfDepartment' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Department)],
        ['query'],
      ),
    'getSortedComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDepartment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'updateDepartmentComplaintStatus' : IDL.Func(
        [IDL.Text, ComplaintStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };