/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : string,
  'status' : ComplaintStatus,
  'studentId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'priority' : Priority,
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'inProgress' : null } |
  { 'registered' : null };
export interface Department {
  'id' : bigint,
  'headOfDepartment' : [] | [Principal],
  'name' : string,
  'description' : string,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'departmentId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createComplaint' : ActorMethod<[string, string, Priority], undefined>,
  'createDepartment' : ActorMethod<
    [bigint, string, string, [] | [Principal]],
    undefined
  >,
  'deleteAccount' : ActorMethod<[], string>,
  'deleteDepartment' : ActorMethod<[bigint], undefined>,
  'findUsersByDepartmentId' : ActorMethod<[[] | [bigint]], Array<UserProfile>>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintById' : ActorMethod<[string], Complaint>,
  'getComplaintsByDepartment' : ActorMethod<[], Array<Complaint>>,
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getComplaintsByStudent' : ActorMethod<[Principal], Array<Complaint>>,
  'getDepartment' : ActorMethod<[bigint], Department>,
  'getDepartmentCount' : ActorMethod<[], bigint>,
  'getDepartmentsByHeadOfDepartment' : ActorMethod<
    [Principal],
    Array<Department>
  >,
  'getSortedComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDepartments' : ActorMethod<[], Array<Department>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDepartment' : ActorMethod<
    [bigint, string, string, [] | [Principal]],
    undefined
  >,
  'updateDepartmentComplaintStatus' : ActorMethod<
    [string, ComplaintStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];