/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
  'registered' : IDL.Null,
});
export const Time = IDL.Int;
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'status' : ComplaintStatus,
  'studentId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'priority' : Priority,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createComplaint' : IDL.Func([IDL.Text, IDL.Text, Priority], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintById' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComplaintsByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
    'registered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'status' : ComplaintStatus,
    'studentId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createComplaint' : IDL.Func([IDL.Text, IDL.Text, Priority], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintById' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComplaintsByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateComplaintStatus' : IDL.Func([IDL.Text, ComplaintStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };